#!/usr/bin/env sh

cd `dirname $0`

{
    echo "/* autogenerated by rethemendex.sh */"

    # we used to have exclude /themes from the find at this point.
    # as themes are no longer a spurious subdirectory of css/, we don't
    # need it any more.
    #
    # Exclude _sc/ folder dedicated for our own CSS files from being included
    # to alphabetic sorting which causes cascading mess. Please note that CSS
    # files inside the folder should be imported manually.
    find . -iname _\*.pcss -not -path "./_sc/*" | fgrep -v _components.pcss | LC_ALL=C sort |
        while read i; do
            echo "@import \"$i\";"
        done

        # After the sort conducted above, import the CSS file dedicated
        # for customization to let rules on the file override the styles
        # specified by the upstream project.
        echo "\n/* Customization for SchildiChat */"
        echo "@import \"./_sc/_customization.pcss\";"
} > _components.pcss
